### DISCUSSION TITLE
Grpc web envoy filter config for latest istio version

### DISCUSSION THREAD

**Discussion by pranavnateri** [grpc/grpc-web#1443] [Q&A - Errors / Debugging Help]
hi 
i am actually trying to apply the below mentioned envoy filter of grpc web for one of our microservices..

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bms-operator-platform-service
spec:
  workloadLabels:
    app: bms-operator-platform-service
  filters:
  - listenerMatch:
      listenerType: ANY
      listenerProtocol: HTTP
    insertPosition:
      index: FIRST
    filterType: HTTP
    filterName: "envoy.grpc_web"
    filterConfig: {}
```
 however, i am getting the below error
 
 
`error: error validating "/Users/pnateri/modules/kubernetes-deployment-dev/earth.xpressplay.net/cap-dev/subscription-service/envoy.yaml": error validating data: ValidationError(EnvoyFilter.spec): unknown field "filters" in io.istio.networking.v1alpha3.EnvoyFilter.spec; if you choose to ignore these errors, turn validation off with --validate=false`

its probably because the above envoyfilter config belongs to an old istio version..
now i am currently on a latest istio version running on a EKS cluster(k8s version: 1.21)..  but trying to apply the same envoyfilter config...

can you help me let me know what exactly could be the equivalent envoyfilter config of grpc web for a latest istio version?

Regards,
Pranav
