### ISSUE TITLE
ESPv2 authentication error getting mapped to StatusCode.UNKNOWN

### ISSUE THREAD

**Issue by j4ckofalltrades** [grpc/grpc-web#1023]
I have a gRPC endpoint that sits behind ESPv2 with JWT authentication configured and I'm trying to configure a retry policy that will retry requests when say an invalid / expired JWT is passed in the request.

I was expecting that a HTTP 401 response from ESPv2 would be mapped to `StatusCode.UNAUTHENTICATED` but instead it gets mapped to `StatusCode.UNKNOWN`.

Sample server response:

```
< HTTP/2 401
< date: Tue, 19 Jan 2021 06:54:03 GMT
< content-type: application/json
< content-length: 40
< strict-transport-security: max-age=15724800; includeSubDomains
< access-control-allow-origin: *
< access-control-allow-credentials: true
< access-control-allow-methods: PUT, HEAD, GET, POST, OPTIONS
< access-control-allow-headers: Authorization, X-User-Agent, X-Grpc-Web, Content-Type
<
{"code":401,"message":"Jwt is missing"}
```

This then gets mapped to:

```
{
  code: StatusCode.UNKNOWN,
  message: 'Unknown Content-type received.',
  metadata: {},
}
```

Relevant code seems to be here: https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpcwebclientreadablestream.js#L154-L159

Is there a way to do this?

**Comment by j4ckofalltrades** [comment]
Turns out I was missing `Access-Control-Expose-Headers: Grpc-Message, Grpc-Status` in my CORS policy; closing.

**Comment by LiBa001** [comment]
I got the exact same error, but adding those headers doesn't change anything. I think the problem is, that the server returns a content type `application/json` in case of an error, when usually it returns `application/grpc-web+proto`. Therefore, it is an unknown content type.
Now I don't know whether the problem lies somewhere in my ESPv2 configuration which causes it to return the wrong content type or it is normal for `applictation/json` to be returned on errors (probably the former, which is why I won't reopen this).

@j4ckofalltrades did you possibly change anything else, besides the CORS expose headers? Cause I don't see how they would've changed the content type.

**Comment by j4ckofalltrades** [comment]
@LiBa001 Thanks for pointing this out.

> @j4ckofalltrades did you possibly change anything else, besides the CORS expose headers? Cause I don't see how they would've changed the content type.

Haven't found a solution to this one unfortunately (the other issue I had with the CORS config was unrelated to this one and I forgot to update this issue) -- reopening this issue.

**Comment by nsadeh** [comment]
Hey, my hunch is that the network call is correctly responding with a 401 and that your gRPC client maps that to an UNKNOWN since it cannot parse the headers returned by ESPv2. Basically ESP tried to authenticate your request, couldn't, so it responded to your client using an `application/json` content type saying it couldn't authenticate. Your gRPC client couldn't understand what it was saying so it just said "content type unknown". ESP didn't so much "change" the content type as didn't really care about your original content type as it got stuck in the auth stage.

I am conjecturing this based on my current experience, I am trying to get auth setup on a gRPC backend as well with ESPv2 proxy, and I see my network results as 
```
{"message":"UNAUTHENTICATED:Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.","code":401}
```
but my RPC client says `Unknown Content-type received`. In this case, it means that the client received an unknown content type in the form of JSON.

**Comment by ericb-summit** [comment]
espv2 is envoy based.  Assuming it is possible to control the config, you could use a local reply to rewrite the 401 to something that `grpc-web` will consume.  This works.

```
              local_reply_config:
                mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 401
                          runtime_key: "%RESPONSE_CODE%"
                  headers_to_add:
                    - header:
                        key: "Content-Type"
                        value: 'application/grpc-web+proto'
                      append: false
                    - header:
                        key: "grpc-message"
                        value: 'Not authenticated'
                      append: false
                    - header:
                        key: "grpc-status"
                        value: '16'
                      append: false
                  status_code: 200
                  body:
                    inline_string: ""
                  body_format_override:
                    content_type: "application/grpc-web+proto"
                    text_format: ""
```

**Comment by j4ckofalltrades** [comment]
@ericb-summit Thank you, this works for my use case. Marking issue as closed.

**Comment by betmix-matt** [comment]
For anyone who is using Istio and are having a problem with gRPC web behaving as described in this issue, you can apply the following:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: grpc-web-authorization-envoy-filter
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          typedConfig:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            local_reply_config:
              mappers:
                - filter:
                    and_filter:
                      filters:
                        - or_filter:
                            filters:
                              - status_code_filter:
                                  comparison:
                                    op: EQ
                                    value:
                                      default_value: 401
                                      runtime_key: "%RESPONSE_CODE%"
                              - status_code_filter:
                                  comparison:
                                    op: EQ
                                    value:
                                      default_value: 403
                                      runtime_key: "%RESPONSE_CODE%"
                        - header_filter:
                            header:
                              name: "Accept"
                              exact_match: "application/grpc-web-text"
                  headers_to_add:
                    - header:
                        key: "Content-Type"
                        value: "application/grpc-web-text+proto"
                      append: false
                    - header:
                        key: "grpc-message"
                        value: "Not authenticated"
                      append: false
                    - header:
                        key: "grpc-status"
                        value: "16"
                      append: false
                  status_code: 200
                  body:
                    inline_string: ""
                  body_format_override:
                    content_type: "application/grpc-web-text+proto"
                    text_format: ""
                - filter:
                    and_filter:
                      filters:
                        - or_filter:
                            filters:
                              - status_code_filter:
                                  comparison:
                                    op: EQ
                                    value:
                                      default_value: 401
                                      runtime_key: "%RESPONSE_CODE%"
                              - status_code_filter:
                                  comparison:
                                    op: EQ
                                    value:
                                      default_value: 403
                                      runtime_key: "%RESPONSE_CODE%"
                        - header_filter:
                            header:
                              name: "Accept"
                              exact_match: "application/grpc-web"
                  headers_to_add:
                    - header:
                        key: "Content-Type"
                        value: "application/grpc-web+proto"
                      append: false
                    - header:
                        key: "grpc-message"
                        value: "Not authenticated"
                      append: false
                    - header:
                        key: "grpc-status"
                        value: "16"
                      append: false
                  status_code: 200
                  body:
                    inline_string: ""
                  body_format_override:
                    content_type: "application/grpc-web+proto"
                    text_format: ""
```
