### ISSUE TITLE
Envoy filter not working anymore with envoy >=v1.22

### ISSUE THREAD

**Issue by Gerrit91** [grpc/grpc-web#1220]
With the existing configuration sample from this project and envoy version v1.22, I get the following error message when starting up the proxy:

```
Didn't find a registered implementation for 'envoy.filters.http.grpc_web' with type URL: ''
```

With v1.21 everything works just fine. Is there any way to resolve this problem?

**Comment by shivavishaal66215** [comment]
I'm stuck with the same error too. This might seem silly but someone on StackOverflow fixed this error by changing their envoy file from `envoy.yml` to `envoy.yaml`. @Gerrit91

**Comment by sampajano** [comment]
@shivavishaal66215 that's funny indeed haha.. does changing `yml` -> `yaml` fix the issue for you as well? 😃

**Comment by shivavishaal66215** [comment]
@sampajano Unfortunately it didn't work for me.

**Comment by tomk9** [comment]
Based on https://github.com/envoyproxy/envoy/blob/2586aa6271811ba5653e7da82dfb62c85e740152/examples/front-proxy/service-envoy.yaml#L26:L28
@Gerrit91 @shivavishaal66215 try to add types:

<table>
<tr>
<td> v1.21 </td> <td> v1.22 </td>
</tr>
<tr>
<td>

```yaml
http_filters:
  - name: envoy.filters.http.grpc_web
  - name: envoy.filters.http.cors
  - name: envoy.filters.http.router
```

</td>
<td>

```yaml
http_filters:
  - name: envoy.filters.http.grpc_web
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
  - name: envoy.filters.http.cors
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
  - name: envoy.filters.http.router
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

</td>
</tr>
