### ISSUE TITLE
b is not a function :b({code:2,message:“Incomplete response”} for grpcwebtext, but ok for grpcweb

### ISSUE THREAD

**Issue by yakovdom** [grpc/grpc-web#1264]
Hello!

I am trying to create client for my python grpc server.

My server implements server-side streaming methods and unary calls.
As follows from library documentation, if I need streaming, i should compile my proto files with **mode=grpcwebtext** option

But, I also have following unary call method with bytes field in request:
```
message SaveUserDocumentRequest {
    bytes content = 1;
}

message SaveUserDocumentResponse {
    string url = 1;
}

service MyService {
    rpc SaveUserDocument (SaveUserDocumentRequest) returns (SaveUserDocumentResponse);
}

```

Client code is:
```
uploadImage({ content }, callback) {
        try {
            let realRequest = new SaveUserDocumentRequest();
            realRequest.setContent(content)

            this.client.saveUserDocument(realRequest, {}, (err, response) => {
                if(err) {
                    console.log(err)
                    return;
                }
                callback(response)
            })

        } catch(e) {
            console.log(e)
        }
    }
```

if I compile my protofiles with option **mode=grpcweb** this rpc method works just fine (but other server-streaming methods don't)

But if I compile my protofiles with option **mode=grpcwebtext** and trying to use this method, i got following exception:

> b is not a function :b({code:2,message:“Incomplete response”}

Please, if you know, what am I doing wrong, let me know
Thanks for your help!

**Comment by sampajano** [comment]
Thanks for question :)

Curious if you are using the Envoy proxy as documented here?
https://github.com/grpc/grpc-web#2-run-the-server-and-proxy

**Comment by yakovdom** [comment]
yes, I use envoy

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8921 }
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match: { prefix: "/" }
                        route:
                          cluster: greeter_service
                          timeout: 0s
                          max_stream_duration:
                            grpc_timeout_header_max: 0s
                    cors:
                      allow_origin_string_match:
                        - prefix: "*"
                      allow_methods: GET, PUT, DELETE, POST, OPTIONS
                      allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                      max_age: "1728000"
                      expose_headers: custom-header-1,grpc-status,grpc-message
              http_filters:
                - name: envoy.filters.http.grpc_web
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                - name: envoy.filters.http.cors
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: greeter_service
      connect_timeout: 10.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 50057
```
