### ISSUE TITLE
grpc-web on istio help

### ISSUE THREAD

**Issue by nigeltiany** [grpc/grpc-web#290]
I have fragments of the examples in this project and a go echo server on istio-kubernetes that I can't get to work. If anyone can look at it, just deploy the deploy folder yaml(s). At the moment, the client says the echo server is not available with a 503 return code. Any input here or on the project is appreciated. You can find the project [here](https://github.com/nigeltiany/learning-grpc-web).

**Comment by stanley-cheung** [comment]
Here's an example of using gRPC-Web on Kubernetes: https://github.com/salrashid123/grpc_web_with_gke

**Comment by nigeltiany** [comment]
The example works well. But istio already takes care of envoy ingress and envoy injection into pods. The envoy ingress is preconfigured to work with grpc if a service names a port with the prefix ```grpc```. The envoy ingress is supposed to be pointed to the correct services using virtual services. Here are the configs from the project. Here are some of the configs
```yaml
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
    - port: 9080
      name: grpc-echo         # named port with prefix grpc for istio-envoy's sake
      targetPort: 9080
      protocol: TCP
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
        version: v1
    spec:
      containers:
      - name: echo
        image: echo-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
  selector:
    matchLabels:
      app: echo
```
A virtualservice for the service
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-vs
spec:
  hosts:
  - "*"
  gateways:
  - echo-gateway
  http:
  - match:
    - uri:
        prefix: /echo/EchoService.EchoService
    route:
    - destination:
        host: echo
        port:
          number: 9080
```
Is there anything i'm missing to make it work?
