### ISSUE TITLE
How to use grpc-web in reactjs

### ISSUE THREAD

**Issue by hunnain** [grpc/grpc-web#294]
Hi i have created my grpc server  on nodejs but i want to connect my grpc server with reactjs i want to use grpc web on my react app.
Firstly i write this command 
protoc ./protos/helloworld.proto \
--js_out=import_style=commonjs: \
--grpc-web_out=import_style=commonjs,mode=grpcwebtext:/
to build two file of protocol buffer and this command gives me an error.
protoc-gen-grpc-web: program not found or is not executable
--grpc-web_out: protoc-gen-grpc-web: Plugin failed with status code 1.
when iclone your repo grpc-web and execute command  sudo make install-plugin
so they will give an error 

grpc_generator.cc:20:10: fatal error: google/protobuf/compiler/code_generator.h: No such file or directory
 #include <google/protobuf/compiler/code_generator.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'grpc_generator.o' failed
make[1]: *** [grpc_generator.o] Error 1
make[1]: Leaving directory '/home/hunnain/Apps/ultimatetodo/testing/grpc-web/javascript/net/grpc/web'
Makefile:94: recipe for target 'install-plugin' failed
make: *** [install-plugin] Error 2

please  resolve this error or either please guide me how mai i use grpc-web in my react app.I know this is not an issue but i didn't find any solution and i want to create an app using grpc as soon as possible.

**Comment by stanley-cheung** [comment]
Did you try to compile the plugin on Windows? If so, that's a dupe of #250. Currently compiling the plugin on Windows is only supported via Bazel. Please follow the instructions there.

**Comment by hunnain** [comment]
i am using ubuntu
please guide me stanley i want create an app react app using grpc

**Comment by hunnain** [comment]
Stanley what the procedure to compile or resolve sudo make install-plugin error in ubuntu 18

**Comment by stanley-cheung** [comment]
If you are using Ubuntu, please follow [this](https://github.com/grpc/grpc-web/blob/master/INSTALL.md) instructions. You are probably missing the `git submodule update --init` step.

For how to use gRPC-Web with React, development-process wise there is no significant difference than using any other NPM package at this point. There's a slightly more detailed [tutorial](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/tutorial.md) you can follow.

**Comment by hunnain** [comment]
stanley when i import request file  like this
import {helloRequest} from 'protocolbuffer/helloworld_pb';
const request = new helloworld();
request.name("Hello World")
 so i execute so error comes request.name is not defined
![screenshot from 2018-09-21 06-03-06](https://user-images.githubusercontent.com/24963356/45854438-8b861680-bd64-11e8-9ea8-164ee105f3fb.png)
![screenshot from 2018-09-21 06-02-43](https://user-images.githubusercontent.com/24963356/45854439-8b861680-bd64-11e8-96e3-045836b502eb.png)
![screenshot from 2018-09-21 06-02-35](https://user-images.githubusercontent.com/24963356/45854440-8b861680-bd64-11e8-9d93-3520d4cfbfc8.png)

**Comment by stanley-cheung** [comment]
`request.setName()`?

**Comment by hunnain** [comment]
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc addTodos (AddTodos) returns (AddTodosResponse){}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
// Add todos
message AddTodos {
  int32 id = 1;
  string todo = 2;
  string description = 3;
}
message AddTodosResponse {
  string message = 1;
this is my protofile what are you saying

**Comment by stanley-cheung** [comment]
> this is my protofile what are you saying

for a field with the name `name`, the API to set the field for protobuf is `.setName('Hello')`.

**Comment by hunnain** [comment]
If i write this 
const client = new EchoServiceClient('localhost:8080');
so there was an error come 
EchoServiceClient or Greeter in my case is not a constructor and in port my react port is 3000 and my grpc server port is 50051 so what want to write their

**Comment by hunnain** [comment]
sorry i have using webpack so there was no port in client but there was an error of  Greeter is not a constructor. By the way you write new

**Comment by stanley-cheung** [comment]
try `const client = new GreeterClient('localhost:50051');`

**Comment by hunnain** [comment]
No there was an error client is not a constructor 
![screenshot from 2018-09-21 06-33-51](https://user-images.githubusercontent.com/24963356/45855203-6bf0ed00-bd68-11e8-8ee0-d48b1519c5f5.png)
![screenshot from 2018-09-21 06-33-39](https://user-images.githubusercontent.com/24963356/45855204-6bf0ed00-bd68-11e8-9383-227e9bec167a.png)

**Comment by hunnain** [comment]
Stanley i try your command 
const client = new GreeterClient('localhost:50051');
so again error appear client.echo is not a function

**Comment by hunnain** [comment]
stanley i want to chat with you can  you attach with me on fb its urgent and i want to clear my some confusion.

**Comment by stanley-cheung** [comment]
> client.echo is not a function

Your service's methods are:
```
service Greeter {
// Sends a greeting
rpc SayHello (HelloRequest) returns (HelloReply) {}
rpc addTodos (AddTodos) returns (AddTodosResponse){}
}
```

so you should be doing `client.sayHello()`, or `client.addTodos()`.

**Comment by hunnain** [comment]
Thank you so much stanley you help me there is last error i am facing 
Failed to load localhost:50051/helloworld.Greeter/SayHello: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
i have also instal hhtp and run http server on my root directory so  now client side  port is 8082
what may i do now there was no console on my grpc node server i think because of this error my data is not going in grpc server.
![screenshot from 2018-09-21 15-04-50](https://user-images.githubusercontent.com/24963356/45875073-13454280-bdb0-11e8-9d91-356615a93941.png)

**Comment by hunnain** [comment]
Stanley please guide me this issue help every react or any other library developer to use grpc-web in their apps

**Comment by stanley-cheung** [comment]
You have to deploy a proxy which understands gRPC-Web. The default proxy is [Envoy](https://www.envoyproxy.io/). See the documentation [here in the main page](https://github.com/grpc/grpc-web#2-run-the-server-and-proxy) and [here in the tutorial](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/tutorial.md#configure-the-envoy-proxy).

Basically you need an Envoy config file similar to [this](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml). [Line 10](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L10) is the port number which Envoy listens to your browser requests, whereas [Line 43](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L43) is where Envoy should forward the request to your gRPC backend server.

The error you got is because in browsers, cross-origin requests are, be default, prohibited. You have to add [a section](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L25-L32) to your Envoy config to properly allow for cross-origin requests. For more information about CORS, please see resources similar to this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In the [quick demo](https://github.com/grpc/grpc-web#quick-demo) in our main page, you can see that there's an `envoy` docker image. The relevant Dockerfile is [here](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/docker/envoy/Dockerfile). It is in fact very simple: all you need to do is to run the main `envoy` binary and give it your own Envoy config file.

**Comment by stanley-cheung** [comment]
You can attach authentication headers using the `metadata` argument (usually the 2nd parameter per RPC method). For example:

```
var authHeaders = { 'API-KEY': apiKey };
client.addTodos(req, authHeaders, (err, response) => {
  // ...
});
```

**Comment by hunnain** [comment]
Stanley i followed your all step but again it give me an error code of 12 but no any error message
Stanley i am working on grpc-web from 10 to 15 days. I have also set proxy using docker which is running on port 8080 my client side react port 8081 and my grpc-server port is 9090 as you said that i want to integrate proxy from clientside i call this
`  const client = new TodoServiceClient('http://localhost:8080');`
but again it give me error code of 12 but cant give any message the problem is that until now i didnt connect to my grpc server using browser. I have followed your each and every single step
This is my Envoy Docker file 
`
FROM envoyproxy/envoy:latest
CMD /usr/local/bin/envoy -c ../../envoy.yaml -l trace --log-path /tmp/envoy_info.log`
My docker compose file
`version: '3'
services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/docker/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
    links:
      - echo-server`
My envoy.yaml file
`admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8081 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8081 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: echo_service }
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: 0.0.0.0, port_value: 9090 }}]`
My client side React code 
`const client = new TodoServiceClient('http://localhost:8080');
  var request = new Todo();
  request.setTodo('My todo');
  // request.setDescription("My description")
  var metadata = {'custom-header-1': 'value1'};
  var call = client.insert(request, metadata, function(err, response) {
    if (err) {
      console.log("My error",err.code);
      console.log("My error message",err.messge);
    } else {
      console.log(response.getMessage());
    }
  });`
![screenshot from 2018-09-26 13-06-31](https://user-images.githubusercontent.com/24963356/46111615-18b3ea00-c201-11e8-9257-2c2c33aa87be.png)
Stanley Thanks that you help me alot for this but please please resolve this because you are the main contributor you can only help me because there is now tutorial of this i am stuck on this.
Thanks you so much

**Comment by hunnain** [comment]
Stanley I am stuck on **last moment** i need your guide i have almost done everything as you told.

**Comment by stanley-cheung** [comment]
You are trying to connect to "localhost:8080" from your client, but your Envoy config is listening at :8081.

**Comment by hunnain** [comment]
Stanley i have also do it 8080 but not working again same erorr

**Comment by stanley-cheung** [comment]
What does your envoy.yaml config look like now?

If you are still stuck, perhaps you can consider starting from the pre-packaged Echo demo? Does that work for you? That should work, as several users have successfully run them. If that work, which it should, you can start modifying from there. Change the .proto file. Change the server. Change the client. Do it one at a time and you can know which issue starts failing, right?

**Comment by hunnain** [comment]
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 } //Stanley i have set it 8080 my proxy is running on port 8080 as you can see in my docker compose file.So stanley i am testing i have changed to 8081 as my clientside port but again i have set it to 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: echo_service }
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
```
Stanley your example is running but the problem is your server in c++ as you have given but i didnt know c++  I think so the main problem is proxy. 
One other thing i want to discuss is that 
`const client = new TodoServiceClient('http://localhost:8080');`
If i remove http from the given code so its give me an error of cross origin cors is enable when i set to http so it cant give cross origin error.

**Comment by stanley-cheung** [comment]
So in your `route_config` section, you are routing all the requests to `cluster: echo_service`. Where is `echo_service` defined? Did you forget to copy the relevant section under the `clusters` tag?

**Comment by hunnain** [comment]
```
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: 0.0.0.0, port_value: 9090 }}]
```
Yeah i have added 
See the screenshot my container is running 
i think everything is fine but what was wrong
![screenshot from 2018-09-28 12-09-40](https://user-images.githubusercontent.com/24963356/46193420-894d2a80-c317-11e8-8943-6f84918f80a7.png)

**Comment by hunnain** [comment]
One more thing stanley when i run Envoy proxy so its give me an error code of 12 and when i run echo-server container its given me an error code of 14 what is this

**Comment by hunnain** [comment]
@stanley-cheung  and @domgreen  basically the main problem is that docs are not clear i have run your example and edit your example 100 times but the problem is when i create my app so it wasnt working i have run server on docker and expose port on  9090 run envoy proxy also when i request to envoy proxy from browser its give me an error code of 14 but when i used node client and direct hit on server they run perfect all configs are same nginx server is also running and i copy your nginx.conf also but not working from web but when i run node client so it working @domgreen i am working on this from 20 days but until now i cant send any request from browser i have try many many things thats why i am contacting with you i know this is open source project and yours time is important but please guide me

**Comment by hunnain** [comment]
@stanley-cheung  I have tried many hting but in react grpcweb is not working as i told you stanley my server and my proxy is fine when i use nodejs client so i can easily do everything but grpc-web is not working i think it was not working on react

**Comment by AnaitBI** [comment]
Hi,
what is the status of this issue?
I'm also struggling with these same issues.

Can't find any way to make it work.

my grpc client is react js, server grpc in csharp
Docker on windows 10 with envoy proxy running.
![image](https://user-images.githubusercontent.com/39155784/49202389-20cd0900-f3ad-11e8-81ce-21163f3a13ed.png)

I run this command and generated my js files (on linux ubuntu 16):
> sudo protoc -I=. proto.proto --js_out=import_style=commonjs:generated --plugin=protoc-gen-grpc-web=/home/grpc-web-master/javascript/net/grpc/web/protoc-gen-grpc-web --grpc-web_out=import_style=commonjs,mode=grpcwebtext:generated

Now in the client side:
```
import { ProtocolServiceClient } from '../output/proto_grpc_web_pb'
import { UserInfo } from "../output/proto_pb";

const grpcHost = "http://127.0.0.1:8085";
const client = new ServiceClient(grpcHost, {}, {});

const request = new UserInfo();
request.setName('a');
const metadata = {};
client.connect(request, metadata ,function(err, response) {
  if (err) {
    console.log(err.code);
    console.log(err.message);
  } else {
    console.log(response);
  }
});
```

Tried to add metaadata to the request with so many types of metadata, nothing worked
```
metadata = {'content-type': 'application/grpc-web-text'};
metadata = {'content-type': 'application/grpc'};
metadata = {'content-type': 'application/grpc-web'};
metadata = {'content-type': 'application/grpc-web+proto'};
metadata = {'content-type': 'application/grpc-web+json'};
```


And the result is:
POST http://127.0.0.1:8085/ProtocolProtos.ProtocolService/Connect 503 (Service Unavailable)
And receive back a gRPC error code 14 => upstream connect error or disconnect/reset before headers

What am I missing?
@johanbrandhorst @JBetser @mier85 
Please help me, I'm a struggling with this for a very long time.

Here is my envoy.yaml file:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9903
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8085
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: protocol_service
                  max_grpc_timeout: 10s
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: protocol_service
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    # dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts:
      - socket_address:
          address: 0.0.0.0
          port_value: 9090
```

And here is my Dockerfile:
```
FROM envoyproxy/envoy:latest
COPY envoy.yaml /etc/envoy/envoy.yaml
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```
To run the image I did:
> docker build -f envoyDockerfile -t envoy:v14 .
> docker run -d --name envoyv148085 -p 9903:9903 -p 8085:8085 envoy:v14
