### ISSUE TITLE
How to set grpc web client path? Help wanted

### ISSUE THREAD

**Issue by weilip1803** [grpc/grpc-web#335]
How to set grpc web client path? Help wanted

**Comment by weilip1803** [comment]
I have tried that but for the envoy routes
```
              routes:
              - match: { prefix: "/test" }
                route:
                  cluster: test_service
                  timeout: 0s
```
Grpc code
```
http://localhost:8080/test
```
This will not work. It only works if the prefix is "/"
