### ISSUE TITLE
Help with implementing Stream re-connection for grpc-web. 

### ISSUE THREAD

**Issue by weilip1803** [grpc/grpc-web#384]
Currently, if the grpc service is not active or running, for example if echo service is not available. This only returns a post error request which does not goes into the stream.on('error', ...) callback unlike the nodejs api. Are there plans to make this consistent with the nodejs api? And is waitForReady() going to be implemented also?
```
var stream = echoService.serverStreamingEcho(streamRequest, metadata);
stream.on('error', function(err) {
  console.log(err);
});
```
Even for unary calls, the error does not trigger the call back function. Is that anyway to detect whether the service behind envoy is down a not?

Please let me know if there is another way for me to do graceful re-connection. Thanks in advance

EDIT:
I also noticed something funny about envoy. 
```
virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/a/" }
                route: { cluster: to_a, prefix_rewrite: "/", timeout: 0s }
              - match: { prefix: "/b/" }
                route: { cluster: to_b, prefix_rewrite: "/", timeout: 0s }
              - match: { prefix: "/c/" }
                route: { cluster: to_c, prefix_rewrite: "/", timeout: 0s }
```
Once one of the services disconnect, and I try to connect to another service which is available, envoy dosent seem to work anymore. 
1) Start up all service then envoy
2) take down service a.
3) Try to connect to service a with the client
4) Everything becomes not working till i restart envoy
