### ISSUE TITLE
Error callback never invoked for some classes of server response.

### ISSUE THREAD

**Issue by y3llowcake** [grpc/grpc-web#415]
I have a grpc-web server that is returning 200 OK, and grpc-status / grpc-message, but the client javascript is failing to parse it. The observed behavior is that client requests never receive a completion callback from the library. See the request/response sample below.

The case below is likely related to: https://github.com/google/closure-library/issues/946 , however a quick review of the code suggests there may be more cases like this; unexpected server responses aren't correctly handled.

```
Request URL: http://localhost:8090/derp.EchoService/Echo
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:8090
Referrer Policy: no-referrer-when-downgrade

Response Headers:
access-control-allow-credentials: true
access-control-allow-origin: null
content-length: 0
content-type: application/grpc-web+proto
date: Thu, 20 Dec 2018 19:25:32 GMT
grpc-message: upstream connect error or disconnect/reset before headers
grpc-status: 14
server: envoy
Provisional headers are shown
Content-Type: application/grpc-web+proto
grpc-timeout: 999m
Origin: null
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
X-Grpc-Web: 1
X-User-Agent: grpc-web-javascript/0.1
```

**Comment by QuentinBrosse** [comment]
I don't kown if my problem is in the scope of this issue but here is the explanation:
I have a gRPC server written in Go, my proxy is `envoy`, and I use the JS client of `grpc-web` in this mode: `import_style=commonjs,mode=grpcwebtext`.

In case of error, the JS Client don't handle the error. For example, this call return a valid GRPC error in headers:
``````

**Comment by QuentinBrosse** [comment]
Hi @y3llowcake !
I don't kown if my problem is in the scope of this issue but here is the explanation:
I have a gRPC server written in Go, my proxy is `envoy`, and I use the JS client of `grpc-web` in this mode: `import_style=commonjs,mode=grpcwebtext`.

If my server resturns a gRPC error, the JS Client don't handle the error. For example, this call returns a valid GRPC error in headers:
![50375748-e3057e00-0602-11e9-8608-c7771c2e7601](https://user-images.githubusercontent.com/10938538/50375765-0e886880-0603-11e9-88cd-9f9f041db035.png)

but my client don't handle it:
```js
const signUpCall = accountClient.signUp(accountRequest, {}, (err, res) => {
    if (err) {
        console.error(err);
    }
    console.log(res);
});

signUpCall.on('status', status => console.log('status', status));
signUpCall.on('data', d => console.log('data', d));
signUpCall.on('end', d => console.log('end', d));
signUpCall.on('error', d => console.log('error', d));
```
(In this case, none of my `console.log` was called...)

What do you think ? :)
Thanks !

**Comment by evanj** [comment]
I'm running into the same issue while I'm debugging my implementation of a grpc-web server. If I return an incorrectly encoded response, the grpc-web Javascript client just drops it. Instead, I would expect to get a gRPC error response with code INTERNAL probably? I can provide a more detailed reproduction if that would be useful.

**Comment by RXminuS** [comment]
Are you using CORS?

**Comment by yamelsenih** [comment]
Hi everyone, I have the same problem with it.
I have a server running with gRPC for Java and my client is running with Javascript with grpc-web.

I don't sure if exist a error but debugging the server the calling never is requested for then.

Have you a solution for it?


Best regards

**Comment by skyjia** [comment]
I have the same issue.  CORS is allowed and all headers are exposed.

And here is my envoy.yaml:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    
    filter_chains:
      filters:
        - name: envoy.http_connection_manager
          config:
            codec_type: auto
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match: { prefix: "/" }
                  route:
                    cluster: echo_service
                    max_grpc_timeout: 0s
                cors:
                  allow_origin:
                  - "*"
                  allow_methods: GET, PUT, DELETE, POST, OPTIONS
                  allow_headers: "*"
                  max_age: "1728000"
                  expose_headers: "*"
            http_filters:
            - name: envoy.grpc_web
            - name: envoy.cors
            - name: envoy.router
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/cert/localhost.crt"
              private_key:
                filename: "/cert/localhost.key"
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: template-svc-grpc, port_value: 9090 }}]
```

Have you got a solution?

**Comment by aberasarte** [comment]
@skyjia do you see any Javascript error in the browser console?

Take into account that wildcards are not always allowed for the `Access-Control-Expose-Headers` header as stated in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers.

> The value "\*" only counts as a special wildcard value for requests without credentials (requests without HTTP cookies or HTTP authentication information). In requests with credentials, it is treated as the literal header name "*" without special semantics.
Note that the Authorization header can't be wildcarded and always needs to be listed explicitly.

It is always a good idea to avoid wildcards for this kind of settings anyway... I would try to set them explicitly and see if that makes any difference. You can use the [echo demo](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L33) as a reference.

**Comment by skyjia** [comment]
@aberasarte I changed the expose headers and restarted the envoy, this error callback is still never invoked.

```yaml
expose_headers: grpc-status,grpc-message
```

package.json:

```json
 "dependencies": {
    "google-protobuf": "^3.10.0",
    "grpc-web": "^1.0.7",
  },
```

```js
   getUserProfile (accessToken, ouid) {
    const request = new ProtoUserAPI.GetUserProfileRequest()
    request.setOuid(ouid)
    request.setAccessToken(accessToken)

    const metadata = null

    const that = this

    return new Promise((resolve, reject) => {
      that.client.getUserProfile(request, metadata, (err, response) => {
        // #1 never go here when there is an error

        if (err) {
          reject(err.message)
        } else {
          // #2 go here when successful
          resolve(response)
        }
      })
    })
  }
```

The code never goes to `#1` when there is an error reported from underlying gRPC service.  I can see the `grpc-status` and `grpc-message` headers in HTTP response in Chrome devtool.

However, the code can go to `#2` when the RPC call is successful.

**Comment by aberasarte** [comment]
Just to confirm that your problem is not related to CORS, do you see any javascript error in the browser console? 

I guess that you are using a recent version of Envoy but just in case, be sure that your version includes [this fix](https://github.com/envoyproxy/envoy/pull/3852).

**Comment by skyjia** [comment]
@aberasarte I don't see any JS error in console.  I have updated the envoy image to the latest one.

```sh
$ docker pull envoyproxy/envoy
Using default tag: latest
latest: Pulling from envoyproxy/envoy
Digest: sha256:c485247f63de16331fbe56aec8e9d8a83da76ca0fa8dc872691a09b8d99a314f
Status: Image is up to date for envoyproxy/envoy:latest
docker.io/envoyproxy/envoy:latest
```

```sh
$ envoy --version
envoy  version: 44f8c365a1f1798f0af776f6aa64279dc68f5666/1.12.1/Clean/RELEASE/BoringSSL
```

![image](https://user-images.githubusercontent.com/964311/69478310-f1b86e80-0e2b-11ea-9a0c-d010a46cdd74.png)

**Comment by skyjia** [comment]
@aberasarte we have figure out the issue. It's due to an incorrect configuration in our API gateway.

**Comment by smoorsausje** [comment]
@skyjia Could you let me know what exactly the incorrect configuration was? 
We have been stuck with this same the same problem with our app and seem to have a similar environment as you do.

Thanks in advance!

**Comment by vs102000** [comment]
Had a similar issue with grpc-web application in asp.net core 3.1. Could solve it by adding expose headers to cords policy.

app.UseCors(
                options => options.SetIsOriginAllowed(x => _ = true).AllowAnyMethod().AllowAnyHeader()
                    .AllowCredentials()
                    .WithExposedHeaders("X-User-Agent", "X-Grpc-Web", "content-type", "x-grpc-web", "x-user-agent",
                        "grpc-status", "grpc-message")
                    .Build()
            );

**Comment by vs102000** [comment]
the last two fields "grpc-status", "grpc-message" (I did not have them before) made the trick

**Comment by elstr** [comment]
> Had a similar issue with grpc-web application in asp.net core 3.1. Could solve it by adding expose headers to cords policy.
> 
> app.UseCors(
> options => options.SetIsOriginAllowed(x => _ = true).AllowAnyMethod().AllowAnyHeader()
> .AllowCredentials()
> .WithExposedHeaders("X-User-Agent", "X-Grpc-Web", "content-type", "x-grpc-web", "x-user-agent",
> "grpc-status", "grpc-message")
> .Build()
> );

where should this code be? do you have a repo where i can check it out? 
Many thanks

**Comment by skyjia** [comment]
@smoorsausje 

I fixed it with the following cors configuration:

```yaml
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: "keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout"
                expose_headers: grpc-status,grpc-message
                max_age: "1728000"
```
