### ISSUE TITLE
grpc-web client 'end' or 'status' callbacks never called

### ISSUE THREAD

**Issue by subhan-nadeem** [grpc/grpc-web#467]
I have a Java GRPC server with SSL enabled. Every time I make a stream request with my backend, the 'end' and 'status' callbacks are never triggered. The 'data' callback works just fine.

Pinging the same API with a Node.js or Java GRPC client results in a callback to the 'end' callback.

Server is on Linux, client is Windows + Chrome.

Similarly for the helloworld example, if I set 'end' and 'status' callbacks, only the 'status' callback is triggered.

My Envoy configuration is as follows:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 12340
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: ingress_http
                stream_idle_timeout: 0s
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite: <host>
                            cluster: service
                            max_grpc_timeout: 60s
                      cors:
                        allow_origin:
                          - "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                        enabled: true
                http_filters:
                  - name: envoy.grpc_web
                  - name: envoy.cors
                  - name: envoy.router
  clusters:
    - name: service
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      hosts:
        - socket_address:
            address: <host>
            port_value: 443
      tls_context:
        sni: <host>
```
