### ISSUE TITLE
But 'metadata' is not included in OPTIONS request.

### ISSUE THREAD

**Issue by andrewtikhonov** [grpc/grpc-web#476]
Envoy routing is based on headers in metadata. OPTIONS request fails to be properly routed and is responded with 404.

```
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/serviceA" 
                  headers: [{ name: "namespace", exact_match: "SystemA" }]
                route:
                  cluster: "SystemA::serviceA"
                  max_grpc_timeout: 0s
              - match: 
                  prefix: "/serviceA"
                  headers: [{ name: "namespace", exact_match: "SystemB" }]
                route:
                  cluster: "SystemB::serviceA"
                  max_grpc_timeout: 0s
              - match: 

```
