### ISSUE TITLE
AssertionError: Assertion failed with Envoy and GRPC streamed response

### ISSUE THREAD

**Issue by kamilk91** [grpc/grpc-web#718]
Envoy.yaml
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: echo_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin_string_match:
                        - safe_regex:
                            google_re2: {}
                            regex: \*
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,grpc-status, grpc-message
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: x, port_value: 8000 }}]

```

Package.json
```
...
    "google-protobuf": "^3.6.1",
    "grpc-web": "^1.0.0",
...
```

```
push../node_modules/google-protobuf/google-protobuf.js.goog.asserts.AssertionError {message: 
"Assertion failed", reportErrorToServer: true, messagePattern: "Assertion failed", stack: "AssertionError: 
Assertion failed↵    at new push..…ry [as h] (http://127.0.0.1:4200/main.js:1521:41)"}
```

Method without stream like ```getTime()``` which returning int64 works fine, i can parse response. 

But every method using streamed object like ```stream GetItemsResponse``` gives error in Chrome console. 

its my JS method
```
constructor() {
    this.client = new Client('http://127.0.0.1:8080');
  }
  clickStream() {
    var metadata = {'custom-header-1': 'value1'};

    var stream = this.client.getItems(new Empty(), metadata);
    console.log("now stream on data");
    stream.on('data',function(response){
      //console.log(response);
    });
    console.log("now stream on data");
    stream.on('status',function(status){
      console.log(status.code);
    });
console.log("now stream on data");
    stream.on('end',function(end){

    });
```

envoy Dockerfile

```
FROM envoyproxy/envoy-dev:47f83dae752d14b04269d140e724392d38f5d3eb
COPY envoy.yaml /etc/envoy/envoy.yaml

```

also tried on ```grpc-web``` latest and ```protobuf``` latest npm packages.
