### ISSUE TITLE
react native support?

### ISSUE THREAD

**Issue by mickeyreiss** [grpc/grpc-web#90]
Will grpc-web officially support React Native?

[Here](http://facebook.github.io/react-native/releases/next/docs/javascript-environment.html)'s some more information about what that javascript execution environment looks like on various platforms.

Thanks!

**Comment by richard-joseph-dunelm** [comment]
*Any updates, did anyone get this working working with React-Native (RN)?*

@deltaskelta Forgive me if I'm wrong but, I believe RN's code doesn't have direct access to a browser 'DOM' or XHR etc, so, it is possible that this project makes use of components not directly exposed in RN project code.

**Comment by sixman9** [comment]
Any updates, did anyone get this working working with React-Native (RN)?

@deltaskelta Forgive me if I'm wrong but, I believe RN's code doesn't have direct access to a browser 'DOM' or XHR etc, so, it is possible that this project makes use of components not directly exposed in RN project code.

**Comment by wenbozhu** [comment]
It uses polyfill. 

grpc-web uses Google closure as the runtime ... and the new firestore web client has proven working on RN after we fixed one incompatible behavior (in RN) related to xhr. 

https://github.com/google/closure-library/issues/858

I also attempted doing a "fix" in closure, which unfortunately broke <1% gmail clients (maybe due to plugins).

So, if you are familiar with RN, do give it a retry and report back any issues.

Thanks.

**Comment by Isko97** [comment]
I tried to get it working with React Native.
`var proto = require("./compiled.js");

export default class App extends React.Component {
    constructor(props){
        super(props);

        var service = new proto.proto.EchoServiceClient("http://localhost:8080");
        var unary_request = new proto.proto.EchoRequest();
        unary_request.setMessage("SvenGeorg");
        service.echo(unary_request, {}, function(err, response){
            console.log("Unary echo response: " + response.getMessage());
        });
    }`

**Comment by Isko97** [comment]
I tried to get this running with React Native.
Snippet of my App.js
`var proto = require("./compiled.js");

export default class App extends React.Component {
    constructor(props){
        super(props);

        var service = new proto.proto.EchoServiceClient("http://localhost:8080");
        var unary_request = new proto.proto.EchoRequest();
        unary_request.setMessage("Test");
        service.echo(unary_request, {}, function(err, response){
            console.log("Unary echo response: " + response.getMessage());
        });
    }
    // render...`

At the end of the compiled.js I added the following to allow including the modal.
`exports.proto = proto.grpc.gateway.testing;`
I ran the backend server and nginx using docker.
Unfortunately, I am getting this error: 
`Unknown base64 encoding at char: :
c
compiled.js:429:210`

**Comment by stanley-cheung** [comment]
Did you compile Nginx from this repo or you use a standard Nginx?

**Comment by Isko97** [comment]
I followed the instruction of the INSTALL.md and of the echo example. The nginx version is nginx/1.11.13.

**Comment by ademcan** [comment]
I am also trying to get the grpc-web running on React-Native to avoid using code duplication for iOS and Android. I managed to generate the compiled.js file but everytime I want to "load" it I have an error. I tried both of the following options:
import './compiled.js';
var proto = require('./compiled.js');
But none of these work. 
Did someone here managed to use the grpc-web with RN.
Thank you for your help.

**Comment by trungthanhnt** [comment]
Is there any update of trying grpc-web in React-Native?

**Comment by hugows** [comment]
Is there any update of trying grpc-web in React-Native?

**Comment by wenbozhu** [comment]
Sorry, we don't have any local expertise to debug grpc-web on RN. We do know that goog-closure and its networking module (that grpc-web depends on) work fine on RN (e.g. in firestore/web). 

So, if any of you likes to spend some serious time debugging the environment and working with us to get to the bottom of this, let me know. Thanks.

**Comment by lyseiha** [comment]
+1

**Comment by fr3fou** [comment]
any news?

**Comment by Pearcekieser** [comment]
+1 I'd like this too, I might be able to help support.  What is the current state of this

**Comment by shotor** [comment]
For those waiting for this, if it helps: I was able to use grpc-web in a react-native expo app without any problems. Not sure how this relates to react-native without expo.

Code: https://github.com/tihu-nlp/tihu-native/blob/master/app/src/logic/api/speak.ts

**Comment by SameeraMadushan** [comment]
Is there any work around for grpc-web with react-native cli app?

**Comment by PrimeTimeTran** [comment]
We're also having problems with RN as documented in [this question](https://stackoverflow.com/questions/62295689/how-to-generate-protocol-buffers-for-ios-release-build-react-native)  on Stack.

[How to generate protocol buffers for iOS Release build React Native](https://stackoverflow.com/questions/62295689/how-to-generate-protocol-buffers-for-ios-release-build-react-native)

We haven't seen documentation that addresses this issue. Anyone have experience and would like to help? Thank you in advance~!

**Comment by virtumonde** [comment]
@shotor is right, you are able to connect from React Native. Here is a Docker example where the server uses Go.

```docker-compose.yml```
```
version: "3.8"
services:
  envoy:
    build: ./envoy
    restart: always
    expose:
      - "2301"
    ports:
      - "2301:2301"
  server:
    build: ./server
    depends_on:
      - postgres
      - envoy
    ports:
      - "2302:2302"
    restart: always
```
The gRPC service (server) listens for connections on ```2302``` while the ```envoy``` proxy listens on ``2301``` and redirects to ```2302```, which is the gRPC service.

```Dockerfile for envoy```:
FROM envoyproxy/envoy-alpine:v1.14-latest
COPY envoy.yaml /etc/envoy/envoy.yaml

```envoy.yaml```:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 2301 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: greeter_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: greeter_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: host.docker.internal
                    port_value: 2302
```
As I am using an Apple laptop, I use ```host.docker.internal``` instead of localhost for ```address``` in ```socket_address```.
