### ISSUE TITLE
Error status and message for server-side streams

### ISSUE THREAD

**Issue by merlinnot** [grpc/grpc-web#901]
Hi! I bumped into an issue where gRPC errors are not translated/propagated correctly from a gRPC stream. While researching the issue, I learned that there are two headers responsible for this: grpc-status, grpc-message. However for streams we can't set headers (we'd need trailers). Is it somehow covered by the protocol design/implementation, or do I have to come up with something custom?

**Comment by stanley-cheung** [comment]
Which server language are you using? The answer might be different. But in general, you shouldn't _need to_ know about the `grpc-status` and the `grpc-message` header to be able to communicate trailers metadata.

Here's an example in the Node server. In our interop test, [here](https://github.com/grpc/grpc-node/blob/master/test/interop/interop_server.js#L144) is how the Node server is setting the trailing metadata. On the grpc-web JS client side, we check the trailing metadata [here](https://github.com/grpc/grpc-web/blob/master/test/interop/interop_client.js#L127). (Although the interop test example is sending a unary call, the API is the same for server streaming calls). So as you can see, under normal circumstances, for unary and server streaming calls, you don't really need to know about `grpc-status` or `grpc-message`.

Now there are also the _initial_ metadata. [Here](https://github.com/grpc/grpc-node/blob/master/test/interop/interop_server.js#L60) is an example of how the Node server sends the initial metadata. And [here](https://github.com/grpc/grpc-web/blob/master/test/interop/interop_client.js#L121) is how you check it on the JS client side. There you still don't need to know about `grpc-status` or `grpc-message`. But here's it gets a little tricky - initial metadata are represented as http response headers. Specifically for web, normally, custom response headers are not exposed to user. You need to specifically set the `Access-Control-Expose-Header` header to tell the browser to allow that header to be bubbled up to the user. So for grpc-web, you need to explicitly tell Envoy to set that header, like [this](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml#L34). But once those headers are properly being exposed in the browser API, we have additional logic already in our client library to [handle](https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpcwebclientreadablestream.js#L185) them, so you still don't really need to set them (or retrieve them) explicitly.

Hope this helps.

**Comment by merlinnot** [comment]
This is very helpful, mostly because it's very uplifting to see maintainers read through issues carefully and provide such detailed answers, you're awesome!

I did see the interop test before and I think I'm doing it correctly:

```ts
// Server code.
stream.emit('error', {
  code: google.rpc.Code.UNAUTHENTICATED,
  message: 'Authentication failed.',
})
```

I also created and tested a Node.js client and I do get a correct error:

```ts
// Client code.
stream.on("error", (error: Error): void => {
  console.error(error);
});


// Error: 16 UNAUTHENTICATED: Authentication failed.
```

In front of that server I have an Envoy proxy, currently I'm using 1.14.3, with the following configuration:

<details>
  <summary>Long block, click to expand!</summary>
  
  ```yaml
  admin:
    access_log_path: /dev/null
  static_resources:
    clusters:
      - connect_timeout: 30s
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        load_assignment:
          cluster_name: my-api
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: my.run.app
                        port_value: 443
        name: my-api
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
            common_tls_context:
              alpn_protocols: 'h2'
            sni: my.run.app
        type: LOGICAL_DNS
    listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
            protocol: TCP
        filter_chains:
          - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                  codec_type: auto
                  http_filters:
                    - name: envoy.filters.http.grpc_web
                    - name: envoy.filters.http.cors
                    - name: envoy.filters.http.router
                  access_log:
                    - name: envoy.file_access_log
                      config:
                        path: /dev/stdout
                  route_config:
                    name: local-route
                    virtual_hosts:
                      - cors:
                          allow_headers: 'keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,token'
                          allow_methods: 'GET, PUT, DELETE, POST, OPTIONS'
                          allow_origin_string_match:
                            - prefix: '*'
                          expose_headers: 'grpc-status,grpc-message'
                          max_age: '1728000'
                        domains:
                          - '*'
                        name: local-service
                        routes:
                          - match:
                              prefix: /
                            route:
                              cluster: my-api
                              host_rewrite: my.run.app
                              max_grpc_timeout: 0s
                  stat_prefix: ingress_http
        name: listener-0
  ```
</details>

With this in place, when I call it using `grpc-web`, I get an `end` event, but no `error` nor `status` events.

Since you mentioned interop tests, I'll try to be more helpful and come up with a reproduction for it.
