### ISSUE TITLE
The latest envoy.yaml does not match the example shown in README.md

### ISSUE THREAD

**Issue by phamvh** [grpc/grpc-web#921]
In grpc-web/net/grpc/gateway/examples/helloworld, the envoy.yaml has changed, but the README.md still shows part of the old version of that file. When I run it, got an error on console, saying:
`Unexpected error for sayHello: code = 14, message = "upstream connect error or disconnect/reset before headers. reset reason: connection failure"`
The static server (the one run with python) shows:
`127.0.0.1 - - [06/Aug/2020 21:27:24] "GET / HTTP/1.1" 304 -`
I checked the file /tmp/admin_access.log, but it's empty.
Here is the command I used to run on mac os:
`docker run -d -v "$(pwd)"/envoy.yaml:/etc/envoy/envoy.yaml:ro -p 8080:8080 -p 9901:9901 envoyproxy/envoy:v1.15.0`

Please kindly guide me through what can be adjusted here. Plz note that the old version (pulled around Jan 2020) worked fine, but it stopped working since I pulled the latest. Have also run `npm rebuild` but that didn't help.

Also, if possible, it would be great if you can add explanations for the different ports used/shown in the README file. There are a number of them, and it's a bit confusing to understand the meaning of 8080 vs 8081, and 9090 vs 9901:
1. 9901 - the envoy admin port
2. 8081 - static web server
3. 9090 - grpc server
4. In envoy.yaml, it seems to state that the forwarding happens from 8080 to 9090, but then in the docker command above, it seems to be 9901 (admin port) that things get forwarded to. Shouldn't it be 9090 in the docker command that runs the envoy proxy? I tried that, but it says 9090 has already been used.

**Comment by phamvh** [comment]
So I was debugging myself, and changed a few things back and forth. Decided to remove this:
    ```
load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 9090
```
and replace that with this:
`hosts: [{ socket_address: { address: host.docker.internal, port_value: 9090 }}]`
then thing started to work again. Anyway, still would like to hear your answers to my questions above. thanks
